# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var $all\
[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[➜](238)"
error_symbol = "[✗](238)"

# [os]
# disabled = false
# format = "$symbol "

# # Shows an icon that should be included by zshrc script based on the distribution or os
# [env_var.STARSHIP_DISTRO]
# format = '[$env_value](bold 208)'  # removed space between distro and rest for pwsh
# variable = "STARSHIP_DISTRO"
# disabled = false

[username]
style_user = "210 bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false  # disable in powershell
show_always = true

[hostname]
ssh_only = false
format = "on [MacBook-Pro](bold 223) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "󰋜 ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold red"

[memory_usage]
disabled = false
threshold = -1
symbol = " 󰍛"
style = "dimmed 70"
format = "[$symbol ${ram}]($style) "

[git_branch]
symbol = "󰊢 "
format = "on [$symbol$branch]($style) "
truncation_length = 20
truncation_symbol = "…/"
style = "bold 208"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "󱚟 "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = " "

[package]
symbol = "󰏗 "

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[helm]
format = "via [ $version](bold purple) "

[docker_context]
symbol = "󰡨 "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[kubernetes]
format = 'on [󱃾 $context\($namespace\)](bold purple) '
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

[aws]
symbol = "  "

[conda]
symbol = " "

[nodejs]
format = "via [ $version](bold green) "

[python]
symbol = " "
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = "󰟓 "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nix_shell]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[lua]
symbol = " "
