command_timeout = 1000

add_newline = true

# Change the default prompt format
# format = """\
# [╭╴](238)$env_var $all\
# [╰─](238)$character"""

format = """\
$os \
$env_var \
$all\
$fill\
$nodejs\
$lua\
$rust\
$java\
$kotlin\
$c\
$golang\
$python\
$haskell\
$gradle\
$package\
$battery $memory_usage $cmd_duration\
$line_break \
$character"""

palette = 'rose_pine_moon'

[palettes.rose_pine_moon]
base = '#232136'
surface = '#2a273f'
overlay = '#393552'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
gold_less = '#eba03b'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
green = '#82968a'
highlight_low = '#2a283e'
highlight_med = '#44415a'
highlight_high = '#56526e'

[fill]
symbol = " "

[character]
success_symbol = "[➜](pine)"
error_symbol = "[➜](love)"

[battery]
disabled = false
discharging_symbol = "󰯈 "

[[battery.display]]
threshold = 5
style = 'bold love'
charging_symbol = '󰂉 '

[os]
disabled = true
style = "fg:color_fg0"
# format = "$symbol "

# # Shows an icon that should be included by zshrc script based on the distribution or os
# [env_var.STARSHIP_DISTRO]
# format = '[$env_value](bold 208)'  # removed space between distro and rest for pwsh
# variable = "STARSHIP_DISTRO"
# disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
style_user = "fg:rose bold"
style_root = "fg:rose bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "󰒋"
format = "on [$ssh_symbol$hostname](bold iris) "
trim_at = "."
disabled = true

[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = "  "
style = 'bold foam'
read_only_style = "love"
read_only = "  "
format = "at [$read_only]($read_only_style)[$path]($style) "

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold love"
format = "[󱫑 $duration]($style) "

[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛"
style = "pine"
format = "[$symbol ${ram}]($style) "

[git_branch]
symbol = "󰊢 "
format = "on [$symbol$branch]($style) "
truncation_length = 30
truncation_symbol = "…/"
style = "bold gold_less"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "󱚟 "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = " "

[package]
symbol = "󰏗 "
format = "[$symbol$version](gold_less) "

[terraform]
symbol = " "
format = "via [$symbol$version]($style) [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[helm]
format = "via [ $version](bold purple) "

[docker_context]
symbol = "󰡨 "
format = " [$symbol$context]($style) "
style = "69 bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[kubernetes]
format = 'on [󱃾 $context\($namespace\)](bold purple) '
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

[aws]
symbol = "  "

[conda]
symbol = " "

[nodejs]
format = "[ $version](bold green) "

[python]
symbol = " "
pyenv_version_name = true
format = '[$symbol$version (\($virtualenv\))]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[c]
symbol = " "
format = '[$symbol$version](bold 69)'

[ruby]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[golang]
# symbol = "󰟓 "
symbol = " "
format = "[$symbol$version](bold 39)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "[$symbol$version](bold rose) "

[julia]
symbol = " "

[nix_shell]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[rust]
symbol = " "
format = "[$symbol$version](bold rose) "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[lua]
symbol = " "
format = "[$symbol$version](bold 69) "

[kotlin]
symbol = ' '
kotlin_binary = 'kotlin'
format = "[$symbol$version](bold 165) "

[gradle]
symbol = ' '
format = "[$symbol$version](bold green) "

[haskell]
symbol = ' '
format = "[$symbol$version](bold 55) "
